#include "FinalStateAnalysis/PatTools/plugins/PATPairFinalStateBuilderT.h"
#include "FinalStateAnalysis/DataFormats/interface/DiLeptonFinalStates.h"

typedef PATPairFinalStateBuilderT<ElecElecFinalState> PATElecElecFinalStateProducer;
typedef PATPairFinalStateBuilderT<ElecMuFinalState> PATElecMuFinalStateProducer;
typedef PATPairFinalStateBuilderT<ElecTauFinalState> PATElecTauFinalStateProducer;
typedef PATPairFinalStateBuilderT<ElecPhoFinalState> PATElecPhoFinalStateProducer;
typedef PATPairFinalStateBuilderT<MuMuFinalState> PATMuMuFinalStateProducer;
typedef PATPairFinalStateBuilderT<MuTauFinalState> PATMuTauFinalStateProducer;
typedef PATPairFinalStateBuilderT<MuPhoFinalState> PATMuPhoFinalStateProducer;
typedef PATPairFinalStateBuilderT<TauTauFinalState> PATTauTauFinalStateProducer;
typedef PATPairFinalStateBuilderT<TauPhoFinalState> PATTauPhoFinalStateProducer;
typedef PATPairFinalStateBuilderT<PhoPhoFinalState> PATPhoPhoFinalStateProducer;
typedef PATPairFinalStateBuilderT<MuJetFinalState> PATMuJetFinalStateProducer;
typedef PATPairFinalStateBuilderT<ElecJetFinalState> PATElecJetFinalStateProducer;

#include "FWCore/Framework/interface/MakerMacros.h"
DEFINE_FWK_MODULE(PATElecElecFinalStateProducer);
DEFINE_FWK_MODULE(PATElecMuFinalStateProducer);
DEFINE_FWK_MODULE(PATElecTauFinalStateProducer);
DEFINE_FWK_MODULE(PATElecPhoFinalStateProducer);
DEFINE_FWK_MODULE(PATMuMuFinalStateProducer);
DEFINE_FWK_MODULE(PATMuTauFinalStateProducer);
DEFINE_FWK_MODULE(PATMuPhoFinalStateProducer);
DEFINE_FWK_MODULE(PATTauTauFinalStateProducer);
DEFINE_FWK_MODULE(PATTauPhoFinalStateProducer);
DEFINE_FWK_MODULE(PATPhoPhoFinalStateProducer);
DEFINE_FWK_MODULE(PATMuJetFinalStateProducer);
DEFINE_FWK_MODULE(PATElecJetFinalStateProducer);

