#include "FinalStateAnalysis/PatTools/plugins/PATSingleFinalStateBuilderT.h"
#include "FinalStateAnalysis/DataFormats/interface/SingleFinalStates.h"

typedef PATSingleFinalStateBuilderT<ElecFinalState> PATElecFinalStateProducer;
typedef PATSingleFinalStateBuilderT<MuFinalState> PATMuFinalStateProducer;
typedef PATSingleFinalStateBuilderT<TauFinalState> PATTauFinalStateProducer;
typedef PATSingleFinalStateBuilderT<PhoFinalState> PATPhoFinalStateProducer;
typedef PATSingleFinalStateBuilderT<JetFinalState> PATJetFinalStateProducer;

#include "FWCore/Framework/interface/MakerMacros.h"
DEFINE_FWK_MODULE(PATElecFinalStateProducer);
DEFINE_FWK_MODULE(PATMuFinalStateProducer);
DEFINE_FWK_MODULE(PATTauFinalStateProducer);
DEFINE_FWK_MODULE(PATPhoFinalStateProducer);
DEFINE_FWK_MODULE(PATJetFinalStateProducer);

