#include "FinalStateAnalysis/PatTools/plugins/PATTripletFinalStateBuilderT.h"
#include "FinalStateAnalysis/DataFormats/interface/TriLeptonFinalStates.h"

typedef PATTripletFinalStateBuilderT<ElecElecElecFinalState> PATElecElecElecFinalStateProducer;
typedef PATTripletFinalStateBuilderT<ElecElecMuFinalState> PATElecElecMuFinalStateProducer;
typedef PATTripletFinalStateBuilderT<ElecElecTauFinalState> PATElecElecTauFinalStateProducer;
typedef PATTripletFinalStateBuilderT<ElecElecPhoFinalState> PATElecElecPhoFinalStateProducer;
typedef PATTripletFinalStateBuilderT<ElecMuMuFinalState> PATElecMuMuFinalStateProducer;
typedef PATTripletFinalStateBuilderT<ElecMuTauFinalState> PATElecMuTauFinalStateProducer;
typedef PATTripletFinalStateBuilderT<ElecMuPhoFinalState> PATElecMuPhoFinalStateProducer;
typedef PATTripletFinalStateBuilderT<ElecTauTauFinalState> PATElecTauTauFinalStateProducer;
typedef PATTripletFinalStateBuilderT<ElecPhoPhoFinalState> PATElecPhoPhoFinalStateProducer;
typedef PATTripletFinalStateBuilderT<MuMuMuFinalState> PATMuMuMuFinalStateProducer;
typedef PATTripletFinalStateBuilderT<MuMuTauFinalState> PATMuMuTauFinalStateProducer;
typedef PATTripletFinalStateBuilderT<MuMuPhoFinalState> PATMuMuPhoFinalStateProducer;
typedef PATTripletFinalStateBuilderT<MuTauTauFinalState> PATMuTauTauFinalStateProducer;
typedef PATTripletFinalStateBuilderT<TauTauTauFinalState> PATTauTauTauFinalStateProducer;
typedef PATTripletFinalStateBuilderT<MuPhoPhoFinalState> PATMuPhoPhoFinalStateProducer;
typedef PATTripletFinalStateBuilderT<MuJetJetFinalState> PATMuJetJetFinalStateProducer;

#include "FWCore/Framework/interface/MakerMacros.h"

DEFINE_FWK_MODULE(PATElecElecElecFinalStateProducer);
DEFINE_FWK_MODULE(PATElecElecMuFinalStateProducer);
DEFINE_FWK_MODULE(PATElecElecTauFinalStateProducer);
DEFINE_FWK_MODULE(PATElecElecPhoFinalStateProducer);
DEFINE_FWK_MODULE(PATElecMuMuFinalStateProducer);
DEFINE_FWK_MODULE(PATElecMuTauFinalStateProducer);
DEFINE_FWK_MODULE(PATElecMuPhoFinalStateProducer);
DEFINE_FWK_MODULE(PATElecTauTauFinalStateProducer);
DEFINE_FWK_MODULE(PATElecPhoPhoFinalStateProducer);
DEFINE_FWK_MODULE(PATMuMuMuFinalStateProducer);
DEFINE_FWK_MODULE(PATMuMuTauFinalStateProducer);
DEFINE_FWK_MODULE(PATMuMuPhoFinalStateProducer);
DEFINE_FWK_MODULE(PATMuTauTauFinalStateProducer);
DEFINE_FWK_MODULE(PATTauTauTauFinalStateProducer);
DEFINE_FWK_MODULE(PATMuPhoPhoFinalStateProducer);
DEFINE_FWK_MODULE(PATMuJetJetFinalStateProducer);

